const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_GENAI_API_KEY });

const interviewReportSchema = z.object({
  matchScore: z
    .number()
    .describe(
      "A score between 0 and 100 indicating how well the candidate's profile matches the job describe",
    ),
  technicalQuestions: z
    .array(
      z.object({
        question: z
          .string()
          .describe("The technical question can be asked in the interview"),
        intention: z
          .string()
          .describe("The intention of interviewer behind asking this question"),
        answer: z
          .string()
          .describe(
            "How to answer this question, what points to cover, what approach to take etc.",
          ),
      }),
    )
    .describe(
      "Technical questions that can be asked in the interview along with their intention and how to answer them",
    ),
  behavioralQuestions: z
    .array(
      z.object({
        question: z
          .string()
          .describe("The technical question can be asked in the interview"),
        intention: z
          .string()
          .describe("The intention of interviewer behind asking this question"),
        answer: z
          .string()
          .describe(
            "How to answer this question, what points to cover, what approach to take etc.",
          ),
      }),
    )
    .describe(
      "Behavioral questions that can be asked in the interview along with their intention and how to answer them",
    ),
  skillGaps: z
    .array(
      z.object({
        skill: z.string().describe("The skill which the candidate is lacking"),
        severity: z
          .enum(["low", "medium", "high"])
          .describe(
            "The severity of this skill gap, i.e. how important is this skill for the job and how much it can impact the candidate's chances",
          ),
      }),
    )
    .describe(
      "List of skill gaps in the candidate's profile along with their severity",
    ),
  preparationPlan: z
    .array(
      z.object({
        day: z
          .number()
          .describe("The day number in the preparation plan, starting from 1"),
        focus: z
          .string()
          .describe(
            "The main focus of this day in the preparation plan, e.g. data structures, system design, mock interviews etc.",
          ),
        tasks: z
          .array(z.string())
          .describe(
            "List of tasks to be done on this day to follow the preparation plan, e.g. read a specific book or article, solve a set of problems, watch a video etc.",
          ),
      }),
    )
    .describe(
      "A day-wise preparation plan for the candidate to follow in order to prepare for the interview effectively",
    ),
  title: z
    .string()
    .describe(
      "The title of the job for which the interview report is generated",
    ),
});

/**
 * @name generateInterviewReport
 * @description Generate interview report based on provided resume, self description and job description with the help of AI.
 * @returns {Object} Interview report generated by AI based on provided resume, self description and job description
 */
async function generateInterviewReport(
  resume,
  selfDescription,
  jobDescription,
) {
  if (!resume || !selfDescription || !jobDescription) {
    console.error("Resume, Self Description or Job Description is missing");
    return;
  }
  const prompt = `
  Generate a structured interview preparation report for the candidate using the inputs below.

  Resume:
  ${resume}

  Self Description:
  ${selfDescription}

  Job Description:
  ${jobDescription}

  ---

  STRICT INSTRUCTIONS:
  - Return ONLY valid JSON
  - Follow the exact JSON structure shown below
  - Use the provided resume, self-description, and job description to generate content
  - Each item in arrays MUST be an OBJECT
  - Do not flatten structure
  - tasks MUST be an array of strings
  - severity MUST be: low, medium, or high
  - matchScore must reflect how well the candidate fits the job
  - The "answer" field MUST NOT contain a direct answer to the question
  - The "answer" field MUST describe HOW the candidate should answer (guidance, approach, key points)
  - Use phrases like "The candidate should..." or "He/She should explain..."
  - Do NOT provide a complete or final answer

  IMPORTANT:
  Bad example of "answer":
  "Use indexing, caching, and optimized queries to improve performance." ❌

  Good example of "answer":
  "The candidate should discuss indexing strategies, query optimization, caching mechanisms, and provide real-world examples of performance improvements." ✅

  ---

  JSON STRUCTURE EXAMPLE:

  {
    "matchScore": 0,

    "technicalQuestions": [
      {
        "question": "string",
        "intention": "string",
        "answer": "The candidate should explain the approach, covering key concepts, tools, and real-world examples without giving a final scripted answer."
      }
    ],

    "behavioralQuestions": [
      {
        "question": "string",
        "intention": "string",
        "answer": "The candidate should explain the approach, covering key concepts, tools, and real-world examples without giving a final scripted answer."
      }
    ],

    "skillGaps": [
      {
        "skill": "string",
        "severity": "low"
      }
    ],

    "preparationPlan": [
      {
        "day": 1,
        "focus": "string",
        "tasks": ["string", "string"]
      }
    ],

    "title": "string"
  }

  ---

  Now generate the interview report using the candidate's resume, self-description, and the job description.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        temperature: 0.2,
      },
    });
    const parsed = JSON.parse(response.text);

    // const result = interviewReportSchema.safeParse(parsed);
    // if (!result.success) {
    //   console.warn("Validation failed. Attempting simple repair...");

    //   // Flattened arrays → convert to array of objects
    //   const repaired = { ...parsed };

    //   if (Array.isArray(repaired.technicalQuestions)) {
    //     const tq = [];
    //     for (let i = 0; i < repaired.technicalQuestions.length; i += 6) {
    //       tq.push({
    //         question: repaired.technicalQuestions[i + 1] || "",
    //         intention: repaired.technicalQuestions[i + 3] || "",
    //         answer: repaired.technicalQuestions[i + 5] || "",
    //       });
    //     }
    //     repaired.technicalQuestions = tq;
    //   }

    //   if (Array.isArray(repaired.behavioralQuestions)) {
    //     const bq = [];
    //     for (let i = 0; i < repaired.behavioralQuestions.length; i += 6) {
    //       bq.push({
    //         question: repaired.behavioralQuestions[i + 1] || "",
    //         intention: repaired.behavioralQuestions[i + 3] || "",
    //         answer: repaired.behavioralQuestions[i + 5] || "",
    //       });
    //     }
    //     repaired.behavioralQuestions = bq;
    //   }

    //   if (Array.isArray(repaired.skillGaps)) {
    //     const sg = [];
    //     for (let i = 0; i < repaired.skillGaps.length; i += 4) {
    //       sg.push({
    //         skill: repaired.skillGaps[i + 1] || "",
    //         severity: repaired.skillGaps[i + 3] || "low",
    //       });
    //     }
    //     repaired.skillGaps = sg;
    //   }

    //   if (Array.isArray(repaired.preparationPlan)) {
    //     const pp = [];
    //     for (let i = 0; i < repaired.preparationPlan.length; i += 6) {
    //       pp.push({
    //         day: repaired.preparationPlan[i + 1] || 1,
    //         focus: repaired.preparationPlan[i + 3] || "",
    //         tasks: repaired.preparationPlan.slice(i + 5, i + 8).filter(Boolean),
    //       });
    //     }
    //     repaired.preparationPlan = pp;
    //   }

    //   // Ensure required fields
    //   if (!repaired.title) repaired.title = "Interview Report";
    //   if (!repaired.matchScore) repaired.matchScore = 0;

    //   // Validate again
    //   const repairedResult = interviewReportSchema.safeParse(repaired);
    //   if (repairedResult.success) {
    //     parsed = repairedResult.data; // ✅ repaired data
    //     console.log("Repair successful!");
    //   } else {
    //     console.error("Repair failed. Data may be incomplete.");
    //   }
    // }
    return parsed;
  } catch (err) {
    console.error("Error occur while creating report:", err);
    throw err;
  }
}

/**
 * @name generateResumeHtml
 * @description Generate HTML content for the resume based on provided resume text, self description and job description with the help of AI.
 * @returns {Object} Generated HTML content for the resume in JSON format with the key "html"
 */
async function generateResumeHtml({ resume, selfDescription, jobDescription }) {
  console.log("Entering generateResumeHtml with inputs:", {
    resume: resume ? "Provided" : "Missing",
    selfDescription: selfDescription ? "Provided" : "Missing",
    jobDescription: jobDescription ? "Provided" : "Missing",
  });
  const htmlSchema = z.object({
    html: z
      .string()
      .describe(
        "The generated HTML content for the resume, which should be well-structured and styled appropriately for display in a web application. The HTML should include sections for the candidate's name, contact information, summary, work experience, education, skills, and any other relevant information extracted from the resume. The structure should be clean and semantic, using appropriate HTML tags such as <header>, <section>, <article>, <h1>, <h2>, <p>, <ul>, <li>, etc. The styling can be basic but should ensure readability and a professional appearance.",
      ),
  });
  const prompt = `You are given a FIXED professional ATS-approved HTML resume template.

Your task:

* Fill the template using ONLY the provided data
* DO NOT add any new sections or information
* DO NOT include a section if no data exists for it
* ONLY replace placeholders with real data

Inputs:

* Resume: ${resume}
* Self Description: ${selfDescription}
* Job Description: ${jobDescription}

STRICT RULES:

1. Data Integrity (CRITICAL):

* Use ONLY the information provided
* DO NOT add, assume, or generate any missing data
* If a section (e.g., Certifications, Projects) has no data → REMOVE that section completely from HTML

2. Structure Control:

* Do NOT create new sections
* Do NOT rename sections
* Do NOT add empty headings
* Keep only sections that have real content

3. Writing Style:

* Rewrite content to sound natural and human-written
* Keep it concise and professional
* No AI-like or generic phrasing

4. Links (IMPORTANT):

* Make LinkedIn, GitHub, or any URLs clickable using: <a href="URL" target="_blank">Link Name</a>

5. Output Format:

* Return ONLY JSON:
  { "html": "<complete HTML here>" }

---

## TEMPLATE:

<html>
<head>
<style>
body {
  font-family: "Helvetica", Arial, sans-serif;
  font-size: 13.5px;
  line-height: 1.5;
  color: #222;
  max-width: 800px;
  margin: auto;
  padding: 20px;
}
h1 {
  font-size: 26px;
  margin-bottom: 5px;
}
.contact {
  font-size: 12.5px;
  color: #555;
  margin-bottom: 15px;
}
h2 {
  font-size: 14px;
  margin-top: 18px;
  margin-bottom: 6px;
  border-bottom: 1px solid #ddd;
  text-transform: uppercase;
}
p {
  margin: 4px 0;
}
ul {
  margin: 5px 0;
  padding-left: 18px;
}
li {
  margin-bottom: 4px;
}
</style>
</head>

<body>

<h1>{{FULL_NAME}}</h1>
<div class="contact">
{{EMAIL}} | {{PHONE}} | {{LOCATION}} | {{LINKS}}
</div>

<h2>Summary</h2>
<p>{{SUMMARY}}</p>

<h2>Skills</h2>
<p>{{SKILLS}}</p>

<h2>Experience</h2>
{{EXPERIENCE}}

<h2>Projects</h2>
{{PROJECTS}}

<h2>Education</h2>
{{EDUCATION}}

<h2>Certifications</h2>
{{CERTIFICATIONS}}

</body>
</html>

---

PLACEHOLDER RULES:

* Replace all {{...}} fields with actual data

* If any section has NO data:
  → REMOVE its <h2> and content completely

* EXPERIENCE & PROJECTS format:

<p><strong>Role – Company</strong> | Duration</p>
<ul>
  <li>Achievement or responsibility</li>
</ul>

* LINKS format example: <a href="https://linkedin.com/in/xyz" target="_blank">LinkedIn</a> | <a href="https://github.com/xyz" target="_blank">GitHub</a>

---
`;
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      temperature: 0.2,
      responseSchema: zodToJsonSchema(htmlSchema),
    },
  });
  const parsed = JSON.parse(response.text);
  const result = htmlSchema.safeParse(parsed);
  if (!result.success) {
    console.error("Validation failed for generated HTML content.");
    throw new Error("Invalid HTML content generated.");
  }
  console.log("Leaving generateResumeHtml with generated HTML content.");
  return parsed.html;
}
/**
 * @name htmlToPdf
 * @description Convert the provided HTML content into a PDF buffer using Puppeteer.
 * @returns {Buffer} PDF buffer generated from the provided HTML content
 */
async function htmlToPdf(htmlResume) {
  let pdfBuffer = null;
  try {
    console.log("Entering htmlToPdf");
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlResume);
    pdfBuffer = await page.pdf({
      format: "A4",
      margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" },
    });
    await browser.close();
    console.log("Leaving htmlToPdf");
  } catch (err) {
    console.error("Error in htmlToPdf:", err.message);
  } finally {
    return pdfBuffer;
  }
}

module.exports = {
  generateInterviewReport,
  generateResumeHtml,
  htmlToPdf,
};
